sudo: required
language: java
jdk: oraclejdk8
install: pip install codecov

services:
  - docker

script: mvn clean verify

after_success: codecov

#docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

# MONGO DB
#  - export MONGO_DB=scala-cloud-skeleton/mongodb
#  - docker build -t $MONGO_DB:$COMMIT ./mongodb
#  - docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
#  - docker push $MONGO_DB
