FROM java:8-jre
MAINTAINER Oleksandr Kharkovskyi <double2603@gmail.com>

ADD ./target/car-service-1.0.0-SNAPSHOT.jar /app/
CMD ["java", "-jar", "/app/car-service-1.0.0-SNAPSHOT.jar"]

#EXPOSE 8989 2000