FROM java:8-jre
MAINTAINER Oleksandr Kharkovskyi <double2603@gmail.com>

ADD ./target/booking-service-1.0.0-SNAPSHOT.jar /app/
CMD ["java", "-jar", "/app/booking-service-1.0.0-SNAPSHOT.jar"]

#EXPOSE 8989 2000
EXPOSE 4000